# Generated by Django 2.1.3 on 2018-11-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20181128_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Alert',
        ),
    ]
