# Generated by Django 2.1.3 on 2018-11-28 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20181128_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
