# Generated by Django 2.1.3 on 2018-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_alert_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ipAddress',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
